### ISSUE TITLE
ModuleNotFoundError: No module named 'settings'

### ISSUE THREAD

**Issue by UmarIgan** [aisayko/python-gtmetrix#16]
I am trying simply get some page speed insight. I previously installed version  python-gtmetrix-0.2.3. I thought that could be the reason of the problem so i upgrade it via pip but i still have the problem. This is happening when  basically try to import gtmetrix

```
> ```
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-24-401a80a54973> in <module>
> ----> 1 import gtmetrix
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gtmetrix/__init__.py in <module>
> ----> 1 from gtmetrix.interface import *
>       2 from gtmetrix.utils import *
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gtmetrix/interface.py in <module>
> ----> 1 import settings
>       2 
>       3 import requests
>       4 
>       5 import os.path
> 
> ModuleNotFoundError: No module named 'setting
> 
> 
> ```
```

**Comment by atharvakadlag** [comment]
check the directory structure, make sure you have **settings.py** and **interface.py** are in same directory.
```bash
.
├── CHANGES.md
├── LICENSE
├── MANIFEST.in
├── README.md
├── TODO.md
├── gtmetrix
│   ├── __init__.py
│   ├── exceptions.py
│   ├── interface.py        # the file you are running
│   ├── settings.py        # the module that error mentions
│   └── utils.py
├── pytest.ini
├── requirements.txt
├── setup.cfg
├── setup.py
├── tests
│   ├── __init__.py
│   ├── test_gtmetrix_interface.py
│   ├── test_gtmetrix_settings.py
│   └── utils.py
└── tox.ini

2 directories, 19 files
```

**Comment by UmarIgan** [comment]
I checked it but i dont have a directory order as you share. In my directories settings.py and interface.py seems at the same directory. I uninstall it and install again but i have same problem. I feel like this is because of my lack of understanding python and cumputer in general thanks for your answer.
This is what i found when i search for gtmetrix: 

<img width="1114" alt="Screen Shot 2020-05-19 at 00 12 26" src="https://user-images.githubusercontent.com/38042220/82260609-44e82580-9966-11ea-810d-e5e4d231bf96.png">
This is inside gtmetrix file that appears in above picture.

<img width="634" alt="Screen Shot 2020-05-19 at 00 13 07" src="https://user-images.githubusercontent.com/38042220/82260679-6517e480-9966-11ea-913c-06e46af110bc.png">

**Comment by atharvakadlag** [comment]
That seems correct. Did it work?

**Comment by UmarIgan** [comment]
No, i still have the same problem.

Atharva Kadlag <notifications@github.com>, 19 May 2020 Sal, 01:57 tarihinde
şunu yazdı:

**Comment by Vusal-Agayev** [comment]
Edit `interface.py` file:
Replace `import settings` with`from gtmetrix import settings`

**Comment by xiaohongzsy** [comment]
hi,what's the command about check the directory structure for python?
